# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.195.0/containers/rust/.devcontainer/base.Dockerfile
# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
ARG VARIANT="bullseye"
FROM mcr.microsoft.com/devcontainers/rust:1-${VARIANT}

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>




# apt install lsb-release wget software-properties-common gnupg
# wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh
# sudo bash /tmp/llvm.sh 12


# possibly? 12?
# sudo apt-get install libclang-common-11-dev

# apt install default-jdk maven

